version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: report_system_db

    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME:-employee_reports_db}
      POSTGRES_USER: ${DB_USER:-db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strong_db_password}

    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: report_system_web

    restart: always

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8001:8000"

    environment:
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,web}
      TIME_ZONE: ${TIME_ZONE:-Asia/Kolkata}

      DJANGO_SETTINGS_MODULE: config.settings.production

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432

      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}

    volumes:
      - ../../../data/static:/app/staticfiles
      - ../../../data/media:/app/media
      - ../../../data/logs:/app/logs

