# Generated by Django 6.0.6 on 2026-06-29 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('date_format', models.CharField(default='%d %B %Y', help_text='Python strftime format string', max_length=30)),
                ('submission_deadline', models.TimeField(default='23:59', help_text='Daily report submission deadline (HH:MM)')),
                ('footer_text', models.CharField(default='© 2025 My Company. All rights reserved.', max_length=300)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REPORT_CREATED', 'Report Created'), ('REPORT_UPDATED', 'Report Updated'), ('REPORT_DELETED', 'Report Deleted'), ('EMPLOYEE_ADDED', 'Employee Added'), ('EMPLOYEE_EDITED', 'Employee Edited'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DESIGNATION_CREATED', 'Designation Created'), ('DESIGNATION_UPDATED', 'Designation Updated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('EXPORT', 'Data Exported')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
