# Generated by Django 6.0.6 on 2026-06-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DailyReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to='reports.activity')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reports.dailyreport')),
            ],
            options={
                'verbose_name': 'Daily Report Activity',
                'verbose_name_plural': 'Daily Report Activities',
            },
        ),
    ]
